name: dingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

  fonts:
    - family: TrainOne
      fonts:
        - asset: lib/assets/fonts/TrainOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf