name: dingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  proximity_sensor: ^1.3.1
  audioplayers: ^6.0.0

  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  permission_handler: ^10.0.0
  sensors_plus: ^5.0.1
  shared_preferences: ^2.2.3
  firebase_database: ^11.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/


