name: dingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flame: ^1.18.0
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  sensors_plus: ^5.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/background_home.png
    - assets/images/background_workshop.png
    - assets/images/background_games.png
    - assets/images/background_closet.png
    - assets/images/background_image.png
    - assets/images/avatar.png
    - assets/images/money_icon.png


